export const lvl1: Record<string, string> = {
  seq: 'Kidnapper',
  aju: 'Helper',
  ass: 'Assassin',
  esp: 'Spy',
  pob: 'Poor',
  gua: 'Guardian',
  neg: 'Negotiator',
  met: 'Shapeshifter',
  ric: 'Rich',
  vid: 'Seer',
  anj: 'Angel',
  ama: 'Lover',
};

export const lvl2: Record<string, string> = {
  dc: 'Two-Faced',
  sort: 'Lucky',
  ati: 'Shooter',
  arb: 'Sentinel',
  inc: 'Incendiary',
  dit: 'Dictator',
  traf: 'Dealer',
  jui: 'Judge',
  nec: 'Necromancer',
  seg: 'Security',
  emp: 'Entrepreneur',
};

export const lvl3: Record<string, string> = {
  ref: 'Reflex',
  fis: 'Inspector',
  dis: 'Discriminator',
  ora: 'Oracle',
  env: 'Poisoner',
  pol: 'Politician',
  ger: 'Manager',
  usu: 'Usurper',
  fof: 'Gossiper',
  lad: 'Thief',
  sac: 'Sacrifice',
  fal: 'Forger',
};

export const lvl4: Record<string, string> = {
  imp: 'Impostor',
  gc: 'Bodyguard',
  sorr: 'Sneaky',
  del: 'Informer',
  comp: 'Comparator',
  nega: 'Denier',
  espc: 'Speculator',
  apr: 'Opportunist',
  int: 'Intrusive',
  mp: 'Bad Omen',
  trap: 'Cheater',
};

export const lvl5: Record<string, string> = {
  apa: 'Catcher',
  arr: 'Troublemaker',
  ped: 'Beggar',
  cam: 'Cambist',
  agi: 'Loan Shark',
  vir: 'Virus',
  car: 'Cartomancer',
  man: 'Manipulator',
  men: 'Liar',
  intm: 'Intimidator',
  pro: 'Wanted',
  trai: 'Traitor',
};

export const lvladv: Record<string, string> = {
  caradv: 'Cartomancer',
  trapadv: 'Cheater',
  trafadv: 'Dealer',
  det: 'Detective',
  cov: 'Gravedigger',
  ajuadv: 'Helper',
  imo: 'Immortal',
  inf: 'Infiltrator',
  deladv: 'Informer',
  geradv: 'Manager',
  necadv: 'Necromancer',
  oraadv: 'Oracle',
  as: 'Secret Agent',
  vidadv: 'Seer',
  sorradv: 'Sneaky',
  arradv: 'Troublemaker',
};

export const lvlcons: Record<string, string> = {
  far: 'Law of Abundance',
  adt: 'Law of Additive',
  rep: 'Law of Repetition',
  ret: 'Law of Return',
  rid: 'Law of the Ridiculous',
  esc: 'Law of Scarcity',
  sub: 'Law of Subtractive',
  asc: 'Decree of Ascendant',
  coi: 'Decree of Coincidence',
  cas: 'Decree of Couples',
  desc: 'Decree of Descendant',
  dev: 'Decree of Duties',
  var: 'Decree of Exchange Rate Variation',
  heg: 'Decree of Hegemony',
  tri: 'Decree of Taxes',
  part: 'Decree of the Division of Property',
  lim: 'Decree of the Limit',
  mes: 'Decree of the Master',
  ple: 'Decree of the Plebiscite',
  sob: 'Decree of the Sovereign',
  ipm: 'Death Tax',
  hal: 'Halloween',
  ra: 'Land Reform',
  exa: 'Measure of Accuracy',
  ar: 'Measure of Action and Reaction',
  caos: 'Measure of Chaos',
  com: 'Measure of Common Agreement',
  div: 'Measure of Diversity',
  dob: 'Measure of Double',
  tro: 'Measure of Exchange',
  ine: 'Measure of Inertia',
  obt: 'Measure of the Obituary',
  par: 'Measure of Pairs',
  refo: 'Measure of Reinforcements',
  repr: 'Measure of Reprise',
  sup: 'Measure of Surprise',
  prx: 'Measure of the Next',
  for: 'Measure of the Strongest',
  fra: 'Measure of the Weakest',
};

export const levels: Record<string, Record<string, string>> = {
  lvl1,
  lvl2,
  lvl3,
  lvl4,
  lvl5,
  lvladv,
  lvlcons,
};

export type LevelKey = keyof typeof levels;
