export const lvl1: Record<string, string> = {
  ama: 'Lover',
  anj: 'Angel',
  aju: 'Helper',
  ass: 'Assassin',
  esp: 'Spy',
  gua: 'Guardian',
  met: 'Shapeshifter',
  neg: 'Negotiator',
  pob: 'Poor',
  ric: 'Rich',
  seq: 'Kidnapper',
  vid: 'Seer',
};

export const lvl2: Record<string, string> = {
  arb: 'Referee',
  ati: 'Shooter',
  dc: 'Two-Faced',
  dit: 'Dictator',
  emp: 'Entrepreneur',
  inc: 'Arsonist',
  jui: 'Judge',
  mp: 'Bad Omen',
  nec: 'Necromancer',
  sort: 'Lucky',
  traf: 'Dealer',
};

export const lvl3: Record<string, string> = {
  dis: 'Discriminator',
  env: 'Poisoner',
  fal: 'Forger',
  fis: 'Inspector',
  fof: 'Gossiper',
  ger: 'Manager',
  lad: 'Thief',
  ora: 'Oracle',
  pol: 'Politician',
  ref: 'Reflection',
  sac: 'Sacrifice',
  usu: 'Usurper',
};

export const lvl4: Record<string, string> = {
  apr: 'Opportunist',
  comp: 'Comparator',
  del: 'Informer',
  espc: 'Speculator',
  gc: 'Bodyguard',
  imp: 'Impostor',
  int: 'Meddler',
  nega: 'Denier',
  seg: 'Security',
  sorr: 'Sneaky',
  trap: 'Cheater',
};

export const lvl5: Record<string, string> = {
  agi: 'Loan Shark',
  apa: 'Catcher',
  arr: 'Troublemaker',
  cam: 'Cambist',
  car: 'Cartomancer',
  intm: 'Intimidator',
  man: 'Manipulator',
  men: 'Liar',
  ped: 'Beggar',
  pro: 'Wanted',
  trai: 'Traitor',
  vir: 'Virus',
};

export const lvladv: Record<string, string> = {
  ajuadv: 'Helper',
  as: 'Secret Agent',
  arradv: 'Troublemaker',
  caradv: 'Cartomancer',
  cov: 'Gravedigger',
  deladv: 'Informer',
  det: 'Detective',
  geradv: 'Manager',
  imo: 'Immortal',
  inf: 'Infiltrator',
  necadv: 'Necromancer',
  oraadv: 'Oracle',
  sorradv: 'Sneaky',
  trafadv: 'Dealer',
  trapadv: 'Cheater',
  vidadv: 'Seer',
};

export const lvlcons: Record<string, string> = {
  ar: 'Action and Reaction',
  adt: 'Additive',
  asc: 'Ascendant',
  com: 'Common Agreement',
  cas: 'Couples Decree',
  coi: 'Coincidence Decree',
  lim: 'Limit Decree',
  mes: 'Master Decree',
  desc: 'Descendant',
  dev: 'Duties',
  esc: 'Scarcity',
  far: 'Abundance',
  hal: 'Halloween',
  heg: 'Hegemony',
  ipm: 'Death Tax',
  ine: 'Inertia',
  rep: 'Law of Repetition',
  rid: 'Law of the Ridiculous',
  ret: 'Law of Return',
  div: 'Diversity Measure',
  sup: 'Surprise Measure',
  tro: 'Exchange Measure',
  caos: 'Chaos Measure',
  dob: 'Double Measure',
  exa: 'Exactness Measure',
  for: 'Strongest Measure',
  fra: 'Weakest Measure',
  prx: 'Next Measure',
  par: 'Pairs Measure',
  obt: 'Obituary',
  part: 'Asset Division',
  ple: 'Plebiscite',
  ra: 'Agrarian Reform',
  refo: 'Reinforcements',
  repr: 'Rerun',
  sob: 'Sovereign',
  sub: 'Subtractive',
  tri: 'Taxes',
  var: 'Subtractive',
};

export const levels: Record<string, Record<string, string>> = {
  lvl1,
  lvl2,
  lvl3,
  lvl4,
  lvl5,
  lvladv,
  lvlcons,
};

export type LevelKey = keyof typeof levels;
