export const lvl1: Record<string, string> = {
  seq: 'Sequestrador',
  aju: 'Ajudante',
  ass: 'Assassino',
  esp: 'Espiã',
  pob: 'Pobre',
  gua: 'Guardião',
  neg: 'Negociante',
  met: 'Metamorfo',
  ric: 'Rica',
  vid: 'Vidente',
  anj: 'Anjo',
  ama: 'Amante',
};

export const lvl2: Record<string, string> = {
  dc: 'Duas Caras',
  sort: 'Sortudo',
  ati: 'Atirador',
  arb: 'Sentinela',
  inc: 'Incendiária',
  dit: 'Ditador',
  traf: 'Traficante',
  jui: 'Juiz',
  nec: 'Necromante',
  seg: 'Segurança',
  emp: 'Empreendedor',
};

export const lvl3: Record<string, string> = {
  ref: 'Reflexo',
  fis: 'Fiscal',
  dis: 'Discriminadora',
  ora: 'Oráculo',
  env: 'Envenenadora',
  pol: 'Político',
  ger: 'Gerente',
  fof: 'Fofoqueira',
  usu: 'Usurpadora',
  lad: 'Ladrão',
  sac: 'Sacrifício',
  fal: 'Falsificadora',
};

export const lvl4: Record<string, string> = {
  imp: 'Impostor',
  gc: 'Guarda-Costas',
  sorr: 'Sorrateira',
  del: 'Delator',
  comp: 'Comparador',
  nega: 'Negacionista',
  espc: 'Especulador',
  apr: 'Aproveitador',
  int: 'Intrometida',
  mp: 'Mau Presságio',
  trap: 'Trapaceira',
};

export const lvl5: Record<string, string> = {
  apa: 'Apanhador',
  ped: 'Pedinte',
  arr: 'Arruaceiro',
  cam: 'Cambista',
  agi: 'Agiota',
  vir: 'Vírus',
  car: 'Cartomante',
  man: 'Manipuladora',
  men: 'Mentirosa',
  intm: 'Intimidador',
  pro: 'Procurado',
  trai: 'Traidora',
};

export const lvladv: Record<string, string> = {
  ajuadv: 'Ajudante',
  as: 'Agente Secreto',
  arradv: 'Arruaceiro',
  caradv: 'Cartomante',
  cov: 'Coveira',
  deladv: 'Delator',
  det: 'Detetive',
  geradv: 'Gerente',
  imo: 'Imortal',
  inf: 'Infiltrado',
  necadv: 'Necromante',
  oraadv: 'Oráculo',
  sorradv: 'Sorrateira',
  trafadv: 'Traficante',
  trapadv: 'Trapaceira',
  vidadv: 'Vidente',
};

export const lvlcons: Record<string, string> = {
  adt: 'Lei do Aditivo',
  esc: 'Lei da Escassez',
  far: 'Lei da Fartura',
  rep: 'Lei da Repetição',
  ret: 'Lei do Retorno',
  rid: 'Lei do Ridículo',
  sub: 'Lei do Subtrativo',
  asc: 'Decreto do Ascendente',
  cas: 'Decreto dos Casais',
  coi: 'Decreto da Coincidência',
  desc: 'Decreto do Descendente',
  dev: 'Decreto dos Deveres',
  heg: 'Decreto da Hegemonia',
  lim: 'Decreto do Limite',
  mes: 'Decreto do Mestre',
  part: 'Decreto da Partilha de Bens',
  ple: 'Decreto do Plebiscito',
  sob: 'Decreto do Soberano',
  tri: 'Decreto dos Tributos',
  var: 'Decreto da Variação Cambial',
  hal: 'Halloween',
  ipm: 'Imposto por Morte',
  ar: 'Medida da Ação e Reação',
  caos: 'Medida do Caos',
  com: 'Medida do Comum Acordo',
  div: 'Medida da Diversidade',
  dob: 'Medida do Dobro',
  exa: 'Medida da Exatidão',
  for: 'Medida do Mais Forte',
  fra: 'Medida do Mais Fraco',
  ine: 'Medida da Inércia',
  par: 'Medida dos Pares',
  prx: 'Medida do Próximo',
  refo: 'Medida dos Reforços',
  repr: 'Medida da Reprise',
  obt: 'Medida do Obituário',
  sup: 'Medida da Surpresa',
  tro: 'Medida da Troca',
  ra: 'Reforma Agrária',
};

export const levels: Record<string, Record<string, string>> = {
  lvl1,
  lvl2,
  lvl3,
  lvl4,
  lvl5,
  lvladv,
  lvlcons,
};

export type LevelKey = keyof typeof levels;
