export const lvl1: Record<string, string> = {
  ama: 'Amante',
  anj: 'Anjo',
  aju: 'Ajudante',
  ass: 'Assassino',
  esp: 'Espiã',
  gua: 'Guardião',
  met: 'Metamorfo',
  neg: 'Negociante',
  pob: 'Pobre',
  ric: 'Rica',
  seq: 'Sequestrador',
  vid: 'Vidente',
};

export const lvl2: Record<string, string> = {
  arb: 'Sentinela',
  ati: 'Atirador',
  dc: 'Duas Caras',
  dit: 'Ditador',
  emp: 'Empreendedor',
  inc: 'Incendiária',
  jui: 'Juiz',
  mp: 'Mau Presságio',
  nec: 'Necromante',
  sort: 'Sortudo',
  traf: 'Traficante',
};

export const lvl3: Record<string, string> = {
  dis: 'Discriminadora',
  env: 'Envenenadora',
  fal: 'Falsificadora',
  fis: 'Fiscal',
  fof: 'Fofoqueira',
  ger: 'Gerente',
  lad: 'Ladrão',
  ora: 'Oráculo',
  pol: 'Político',
  ref: 'Reflexo',
  sac: 'Sacrifício',
  usu: 'Usurpadora',
};

export const lvl4: Record<string, string> = {
  apr: 'Aproveitador',
  comp: 'Comparador',
  del: 'Delator',
  espc: 'Especulador',
  gc: 'Guarda-Costas',
  imp: 'Impostor',
  int: 'Intrometida',
  nega: 'Negacionista',
  seg: 'Segurança',
  sorr: 'Sorrateira',
  trap: 'Trapaceira',
};

export const lvl5: Record<string, string> = {
  agi: 'Agiota',
  apa: 'Apanhador',
  arr: 'Arruaceiro',
  cam: 'Cambista',
  car: 'Cartomante',
  intm: 'Intimidador',
  man: 'Manipuladora',
  men: 'Mentirosa',
  ped: 'Pedinte',
  pro: 'Procurado',
  trai: 'Traidora',
  vir: 'Vírus',
};

export const lvladv: Record<string, string> = {
  ajuadv: 'Ajudante',
  as: 'Agente Secreto',
  arradv: 'Arruaceiro',
  caradv: 'Cartomante',
  cov: 'Coveira',
  deladv: 'Delator',
  det: 'Detetive',
  geradv: 'Gerente',
  imo: 'Imortal',
  inf: 'Infiltrado',
  necadv: 'Necromante',
  oraadv: 'Oráculo',
  sorradv: 'Sorrateira',
  trafadv: 'Traficante',
  trapadv: 'Trapaceira',
  vidadv: 'Vidente',
};

export const lvlcons: Record<string, string> = {
  ar: 'Ação e Reação',
  adt: 'Aditivo',
  asc: 'Ascendente',
  com: 'Comum Acordo',
  cas: 'Decreto dos Casais',
  coi: 'Decreto da Coincidência',
  lim: 'Decreto do Limite',
  mes: 'Decreto do Mestre',
  desc: 'Descendente',
  dev: 'Deveres',
  esc: 'Escassez',
  far: 'Fartura',
  hal: 'Halloween',
  heg: 'Hegemonia',
  ipm: 'Imposto por Morte',
  ine: 'Inércia',
  rep: 'Lei da Repetição',
  rid: 'Lei do Ridículo',
  ret: 'Lei do Retorno',
  div: 'Medida da Diversidade',
  sup: 'Medida da Surpresa',
  tro: 'Medida da Troca',
  caos: 'Medida do Caos',
  dob: 'Medida do Dobro',
  exa: 'Medida da Exatidão',
  for: 'Medida do Mais Forte',
  fra: 'Medida do Mais Fraco',
  prx: 'Medida do Próximo',
  par: 'Medida dos Pares',
  obt: 'Obituário',
  part: 'Partilha de Bens',
  ple: 'Plebiscito',
  ra: 'Reforma Agrária',
  refo: 'Reforços',
  repr: 'Reprise',
  sob: 'Soberano',
  sub: 'Subtrativo',
  tri: 'Tributos',
  var: 'Variação Cambial',
};

export const levels: Record<string, Record<string, string>> = {
  lvl1,
  lvl2,
  lvl3,
  lvl4,
  lvl5,
  lvladv,
  lvlcons,
};

export type LevelKey = keyof typeof levels;
